name: Continuous Delivery
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: CD Export
      - uses: actions/upload-artifact@v4
        with:
          name: calculadorapython
          path: |
            main.py
            README.md